const $=id=>document.getElementById(id);let dashboard=null;
const configuredApiBase=String(window.MAPMARKET_CONFIG?.PUBLIC_API_BASE_URL||'').trim().replace(/\/$/,'');
const labels={FREE:'FREE',PRO:'PRO',BUSINESS:'BUSINESS',BUSINESS_PLUS:'BUSINESS PLUS'};
const money=v=>Number(v||0).toLocaleString('ru-RU')+' сум';
function setError(message=''){ $('error').textContent=message; }
async function load(){const base=$('apiUrl').value.trim().replace(/\/$/,'');const key=$('adminKey').value.trim();if(!base||!key){setError('Укажите URL backend и ADMIN_API_KEY.');return}setError('');$('status').textContent='Загрузка...';try{const r=await fetch(`${base}/admin/dashboard`,{headers:{'x-admin-key':key}});const data=await r.json();if(!r.ok)throw new Error(data.error||`Ошибка HTTP ${r.status}`);dashboard=data;render();$('status').textContent=`Обновлено: ${new Date().toLocaleString('ru-RU')}`}catch(e){dashboard=null;setError(`Не удалось загрузить данные: ${e.message}`);$('status').textContent='';}}
function metric(label,value,note){return `<article class="panel metric"><span>${label}</span><strong>${value}</strong><small>${note}</small></article>`}
function render(){const s=dashboard.summary||{};$('metrics').innerHTML=[metric('Доход в месяц',money(s.projected_monthly_revenue),'сумма активных тарифов'),metric('Магазинов',s.shops_total,'всего в базе'),metric('Активных',s.active_shops,'не заблокированы'),metric('Товаров',s.products_total,'во всех каталогах'),metric('QR использований',s.qr_scans_total,'всего транзакций')].join('');renderBars('plans',dashboard.plans||[],x=>labels[x.plan]||x.plan, x=>`${x.shops_count} магаз. · ${money(x.projected_revenue)}`);renderBars('cities',dashboard.cities||[],x=>x.city,x=>`${x.shops_count} магаз. · ${x.products_count} товаров`);renderShops(dashboard.shops||[])}
function renderBars(id,rows,label,value){const max=Math.max(1,...rows.map(x=>Number(x.shops_count||0)));$(id).innerHTML=rows.length?rows.map(x=>`<div class="bar"><span>${label(x)}</span><span class="track"><span class="fill" style="width:${(x.shops_count/max)*100}%"></span></span><b>${value(x)}</b></div>`).join(''):'<div class="empty">Нет данных</div>'}
function renderShops(rows){const q=($('search').value||'').trim().toLowerCase();const list=rows.filter(x=>`${x.name} ${x.city||''} ${x.plan||''}`.toLowerCase().includes(q));$('shops').innerHTML=list.length?list.map(x=>`<tr><td><strong>${esc(x.name)}</strong><br><small>${esc(x.phone||'')}</small></td><td>${esc(x.city||'Не указан')}</td><td><span class="badge">${labels[x.plan]||esc(x.plan)}</span></td><td>${x.product_count}</td><td>${x.qr_scans_count}</td><td>${esc(x.moderation_status||'active')}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">Магазины не найдены</td></tr>'}
function esc(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}$('apiUrl').value=configuredApiBase;$('load').onclick=load;$('refresh').onclick=load;$('search').oninput=()=>{if(dashboard)renderShops(dashboard.shops||[])};['apiUrl','adminKey'].forEach(id=>$(id).addEventListener('keydown',e=>{if(e.key==='Enter')load()}));
