'use strict';
(() => {
 const main=document.querySelector('main'),nav=document.querySelector('.control-nav');
 const panel=document.createElement('section');panel.className='panel control-panel';panel.dataset.page='compliance';panel.hidden=true;
 panel.innerHTML='<h2>Compliance</h2><button id="complianceReload" class="action">Обновить</button><p id="complianceError" role="alert"></p><div id="complianceSellers"></div><div id="complianceLicenses"></div><h3>Политика лицензирования категорий</h3><div id="compliancePolicy"></div><form id="compliancePolicyForm" class="detail-fields"><label>Утверждённый код категории<input name="category" required maxlength="160"></label><label>Тип лицензии<input name="license_type" maxlength="160"></label><label><input name="required_license" type="checkbox"> Лицензия требуется</label><button class="primary">Сохранить policy</button></form><h3>Юридические документы</h3><p>MARKETPLACE_RULES_CONTENT_REQUIRES_LEGAL_APPROVAL: до публикации утверждённого текста правила не считаются готовыми.</p><form id="compliancePublish" class="detail-fields"><label>Документ<select name="document_type"><option value="terms">Terms</option><option value="privacy">Privacy</option><option value="seller_terms">Seller Terms</option><option value="marketplace_rules">Marketplace Rules</option></select></label><label>Новая версия<input name="version" required maxlength="80" pattern="[A-Za-z0-9._-]+"></label><label>Предоставленный утверждённый текст<textarea name="content" required minlength="20" maxlength="200000" rows="8"></textarea></label><label><input name="approved" type="checkbox" required> Подтверждаю, что текст предоставлен и утверждён</label><button class="primary">Опубликовать новую версию</button></form><h3>Compliance Audit Log</h3><form id="complianceAuditFilters" class="actions"><label>Действие<input name="action"></label><label>Actor ID<input name="actor_id"></label><label>Entity type<input name="entity_type"></label><label>С даты<input type="date" name="from"></label><label>По дату<input type="date" name="to"></label><button class="action">Фильтр</button></form><div id="complianceAudit"></div>';
 const style=document.createElement('style');style.textContent='[data-page=compliance]{overflow-wrap:anywhere;min-width:0}[data-page=compliance] .actions{display:flex;flex-wrap:wrap;gap:12px;align-items:end}[data-page=compliance] .actions label{display:grid;gap:6px;min-width:0;max-width:100%}[data-page=compliance] .table-scroll{overflow:auto;max-width:100%}[data-page=compliance] .detail-fields{display:grid;gap:16px}[data-page=compliance] .detail-fields label{display:grid;gap:6px}';panel.prepend(style);main.append(panel);const link=document.createElement('button');link.type='button';link.dataset.pageButton='compliance';link.textContent='Compliance';nav.append(link);
 const status=s=>({unverified:'Не проверено',pending:'На проверке',verified:'Подтверждено',rejected:'Отклонено'}[s]||s);
 const run=task=>async event=>{event?.preventDefault();$('complianceError').textContent='';try{await task(event);}catch(error){$('complianceError').textContent=error.message;}};
 const decisions=(kind,id,pending)=>pending?`<div class="actions"><button class="action approve" data-compliance-decision="${kind}:${id}:verified">Подтвердить</button><button class="action warn" data-compliance-decision="${kind}:${id}:rejected">Отклонить</button></div>`:'';
 const formBody=id=>Object.fromEntries(new FormData($(id)));
 async function audit(){const query=new URLSearchParams(Object.entries(formBody('complianceAuditFilters')).filter(([,value])=>value));const data=await api('/admin/compliance/audit?'+query);$('complianceAudit').innerHTML='<div class="table-scroll"><table><thead><tr><th>Actor</th><th>Action</th><th>Entity</th><th>Дата</th><th>Metadata</th></tr></thead><tbody>'+data.events.map(e=>`<tr><td>${esc(e.actor_type)} ${esc(e.actor_id)}</td><td>${esc(e.action)}</td><td>${esc(e.entity_type)} ${esc(e.entity_id)}</td><td>${esc(e.created_at)}</td><td><pre>${esc(JSON.stringify(e.metadata,null,2))}</pre></td></tr>`).join('')+'</tbody></table></div>';}
 async function refresh(){
  const [s,l,p]=await Promise.all([api('/admin/compliance/sellers'),api('/admin/compliance/licenses'),api('/admin/compliance/license-requirements')]);
  $('complianceSellers').innerHTML='<h3>Проверка продавцов</h3>'+s.sellers.map(v=>`<article class="panel"><h4>${esc(v.legal_name)} · ${esc(status(v.verification_status))}</h4><p>Seller #${Number(v.id)} · ${esc(v.seller_type)} · Tax ID: ${esc(v.tax_id)}</p><p>Магазины: ${v.shops.map(shop=>esc(shop.name)).join(', ')}</p><p>Отправлено: ${esc(v.submitted_at)}</p>${v.rejection_reason?'<p>'+esc(v.rejection_reason)+'</p>':''}${decisions('seller',v.id,v.verification_status==='pending')}</article>`).join('');
  $('complianceLicenses').innerHTML='<h3>Лицензии магазинов / филиалов</h3>'+l.licenses.map(v=>`<article class="panel"><h4>${esc(v.name)} · ${esc(status(v.license_status))}</h4><p>${esc(v.specialization_code)} · ${esc(v.license_number||'Не отправлена')} · ${esc(v.license_expiry||'')}</p><p>${esc(v.license_rejection_reason||'')}</p>${decisions('license',v.id,v.license_status==='pending')}</article>`).join('');
  $('compliancePolicy').innerHTML=p.categories.map(c=>`<p>${esc(c.category_code)}: ${c.required_license?'требуется':'не требуется'} · ${esc(c.license_type)}</p>`).join('')||'<p>Утверждённая policy ещё не задана. Обычные категории не требуют лицензии.</p>';
  await audit();
 }
 window.YaqintopCompliance={refresh};
 link.onclick=run(()=>window.MapMarketControl.navigate('compliance'));$('complianceReload').onclick=run(refresh);$('complianceAuditFilters').onsubmit=run(audit);
 panel.addEventListener('click',run(async event=>{const button=event.target.closest('[data-compliance-decision]');if(!button)return;const [kind,id,statusValue]=button.dataset.complianceDecision.split(':');const reason=statusValue==='rejected'?window.prompt('Обязательная причина отказа:'):'';if(statusValue==='rejected'&&(!reason||reason.trim().length<3))throw Error('Укажите причину отказа.');button.disabled=true;try{await api(kind==='seller'?`/admin/compliance/sellers/${id}/decision`:`/admin/compliance/shops/${id}/license-decision`,{method:'POST',body:JSON.stringify(kind==='seller'?{verification_status:statusValue,rejection_reason:reason}:{license_verified:statusValue==='verified',reason})});await refresh();}finally{button.disabled=false;}}));
 $('compliancePolicyForm').onsubmit=run(async()=>{const body=formBody('compliancePolicyForm');body.required_license=$('compliancePolicyForm').elements.required_license.checked;await api('/admin/compliance/license-requirements/'+encodeURIComponent(body.category),{method:'PUT',body:JSON.stringify(body)});await refresh();});
 $('compliancePublish').onsubmit=run(async()=>{const form=$('compliancePublish');if(!form.reportValidity())return;const body=formBody('compliancePublish');body.approved=form.elements.approved.checked;if(!window.confirm('Опубликовать эту версию и запросить новое явное согласие пользователей?'))return;await api('/admin/compliance/legal/documents',{method:'POST',body:JSON.stringify(body)});form.reset();await refresh();});
 function clear(){for(const id of ['complianceSellers','complianceLicenses','compliancePolicy','complianceAudit'])$(id).replaceChildren();panel.querySelectorAll('form').forEach(form=>form.reset());$('complianceError').textContent='';}
 window.addEventListener('admin-logout',clear);for(const id of ['apiUrl','adminKey'])$(id).addEventListener('input',clear);
})();
