'use strict';
(() => {
  const main=document.querySelector('main'),nav=main.querySelector('.control-nav');
  const controlled=new Set(['dashboard','stores','users','products','search','qr','moderation','operations','finance','tasks','audit']);
  const titles={stores:'Stores',users:'Users',products:'Products',search:'Search Intelligence',qr:'QR Deals',moderation:'Moderation',operations:'Operations',finance:'Finance',tasks:'Notes',audit:'Audit Log'};
  let config=null,summary=null,current='dashboard',generation=0,sessionTimer,rowsData=[],offset=0;
  const escape=esc,fmt=v=>v===null||v===undefined?'Нет данных':escape(v),when=v=>v?escape(new Date(v).toLocaleString('ru-RU')):'—';
  const table=(items,columns)=>`<div class="table-scroll"><table><thead><tr>${columns.map(([h])=>`<th>${escape(h)}</th>`).join('')}</tr></thead><tbody>${items.map(row=>`<tr>${columns.map(([,fn])=>`<td>${fn(row)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${columns.length}" class="empty">Нет данных за выбранный период</td></tr>`}</tbody></table></div>`;
  const createPanel=(page,html)=>{const e=document.createElement('section');e.className='panel control-panel';e.dataset.page=page;e.hidden=page!==current;e.innerHTML=html;main.append(e);return e;};
  const dashboardPanel=createPanel('dashboard','<h2>Сегодня</h2><div id="opsToday" class="metrics"></div><h2>Требуют внимания</h2><div id="opsAttention" class="actions"></div><h2>Все магазины</h2><p>Последние 10 магазинов; полная таблица, поиск и фильтры — в Stores.</p><div id="opsRecentStores"></div><h2>Финансовые операции</h2><div id="opsDashboardFinance"></div><button id="opsDashboardAddFinance" class="action">Добавить операцию</button><h2>Заметки / задачи</h2><div id="opsDashboardNotes"></div><button id="opsDashboardAddTask" class="action">Добавить задачу</button><h2>Воронки</h2><div id="opsFunnels"></div><h2>География и growth targets</h2><button class="action" id="opsTarget">Установить цель</button><div id="opsGeo"></div>');
  for(const page of ['stores','users','operations','audit']) main.querySelectorAll(`[data-page="${page}"]`).forEach(e=>e.dataset.page='legacy-'+page);
  // Existing legacy tables remain in the DOM for the established renderer.
  $('notes').closest('section').dataset.page='legacy-notes';
  const section=createPanel('ops','<div class="section-title"><h2 id="opsTitle"></h2><div class="actions"><button id="opsAdd" class="primary" hidden>Добавить</button><button id="opsReload" class="action">Обновить раздел</button></div></div><div id="opsFilters" class="ops-filters"></div><div id="opsNotice" class="muted"></div><div id="opsStats" class="metrics"></div><div id="opsRows" aria-live="polite"></div><div id="opsPaging" class="actions"><button id="opsPrev" class="action">Назад</button><span id="opsPageInfo"></span><button id="opsNext" class="action">Далее</button></div>');
  const dialog=document.createElement('dialog');dialog.className='control-dialog';dialog.innerHTML='<button id="opsClose" class="icon-button" aria-label="Закрыть">×</button><div id="opsDetail"></div>';document.body.append(dialog);$('opsClose').onclick=()=>dialog.close();
  const logout=document.createElement('button');logout.className='action';logout.textContent='Выйти';document.querySelector('header').append(logout);
  const logoutAll=document.createElement('button');logoutAll.className='action';logoutAll.textContent='Отозвать admin sessions';document.querySelector('header').append(logoutAll);
  const toast=document.createElement('div');toast.className='ops-toast';toast.setAttribute('role','status');toast.hidden=true;document.body.append(toast);
  function notify(message){toast.textContent=message;toast.hidden=false;setTimeout(()=>toast.hidden=true,4000);}
  function clear(){generation++;clearTimeout(sessionTimer);adminSession=null;$('adminKey').value='';config=null;summary=null;rowsData=[];clearDashboardData();window.MapMarketControl.clearPrivateState();for(const e of [section,dashboardPanel])e.querySelectorAll('#opsRows,#opsStats,#opsToday,#opsAttention,#opsFunnels,#opsGeo,#opsRecentStores,#opsDashboardFinance,#opsDashboardNotes').forEach(x=>x.replaceChildren());$('opsDetail').replaceChildren();dialog.close();$('status').textContent='Сессия закрыта. Введите ключ для входа.';}
  window.addEventListener('admin-logout',clear);
  $('apiUrl').addEventListener('input',clear);
  const safely=fn=>async()=>{setError('');try{await fn();}catch(e){setError(e.message);if([401,403].includes(e.status))clear();}};
  logout.onclick=safely(async()=>{if(adminSession)await api('/admin/session',{method:'DELETE'});clear();});
  logoutAll.onclick=safely(async()=>{const v=await guard('REVOKE ADMIN SESSIONS');if(!v)return;await api('/admin/sessions',{method:'DELETE',body:JSON.stringify(v)});clear();});
  async function login(){
    if(!adminSession){const v=await api('/admin/session',{method:'POST',body:'{}'});adminSession=v;$('adminKey').value='';clearTimeout(sessionTimer);sessionTimer=setTimeout(clear,Math.max(1,new Date(v.expires_at)-Date.now()));}
    if(!config)config=await api('/admin/ops/config');
  }
  async function refresh(){await login();await navigate(current);$('status').textContent='Обновлено: '+new Date().toLocaleString('ru-RU');}
  for(const name of ['load','refresh'])$(name).addEventListener('click',e=>{e.stopImmediatePropagation();safely(refresh)();},true);
  nav.addEventListener('click',e=>{const button=e.target.closest('[data-page-button]');if(!button||!controlled.has(button.dataset.pageButton))return;e.stopImmediatePropagation();safely(()=>navigate(button.dataset.pageButton,true))();},true);
  nav.addEventListener('click',e=>{const button=e.target.closest('[data-page-button]');if(!button||controlled.has(button.dataset.pageButton))return;e.stopImmediatePropagation();safely(async()=>{await login();await load();section.hidden=true;await window.MapMarketControl.navigate(button.dataset.pageButton);})();},true);
  function filters(page){
    const input=(name,label,type='text')=>`<label>${label}<input data-filter="${name}" type="${type}"></label>`;
    const select=(name,label,values)=>`<label>${label}<select data-filter="${name}"><option value="">Все</option>${values.map(v=>`<option value="${escape(Array.isArray(v)?v[0]:v)}">${escape(Array.isArray(v)?v[1]:v)}</option>`).join('')}</select></label>`;
    let html=input('q','Поиск');
    if(['search','qr','finance','audit'].includes(page))html+=select('period','Период',[['today','Today'],['7d','7 days'],['30d','30 days']])+input('from','С даты','date')+input('to','По дату','date');
    if(page==='stores')html+=input('city','Город')+input('district','Район')+input('category','Категория')+select('plan','Тариф',Object.keys(config.plans.reduce((a,p)=>(a[p.name]=p,a),{})))+select('status','Рабочий статус',['active','blocked','disabled'])+select('verification','Проверка',['unverified','verified','rejected'])+select('products','Товары',[['yes','Есть'],['no','Нет']])+select('sort','Сортировка',['name','created','products','activity'])+select('direction','Порядок',['asc','desc']);
    if(page==='users')html+=select('role','Роль',['buyer','seller'])+select('status','Статус',['active','blocked']);
    if(page==='products')html+=input('shop_id','Store ID','number')+input('category','Категория')+input('brand','Бренд')+select('status','Модерация',['active','blocked','rejected'])+select('stock','Наличие',[['yes','Есть'],['no','Нет']]);
    if(page==='search')html+=select('empty','Без результатов',[['true','Только zero results']])+select('sort','Сортировка',['count','last','query']);
    if(page==='qr')html+=input('shop_id','Store ID','number')+select('status','Статус',['CREATED','SELLER_CONFIRMED','BUYER_CONFIRMED','SUCCESS','CANCELLED','EXPIRED']);
    if(page==='finance')html+=select('currency','Валюта',['UZS','USD','EUR'])+select('type','Тип',['income','expense','adjustment'])+select('category','Категория',config.finance_categories);
    if(page==='tasks')html+=select('status','Статус',['TODO','IN_PROGRESS','DONE'])+input('shop_id','Store ID','number');
    if(page==='operations'||page==='moderation')html='';
    $('opsFilters').innerHTML=html+'<button id="opsApply" class="action">Применить</button>';
    $('opsApply').onclick=safely(async()=>{offset=0;await list();});
    $('opsFilters').querySelectorAll('input').forEach(e=>e.onkeydown=event=>{if(event.key==='Enter')$('opsApply').click();});
  }
  function query(){const p=new URLSearchParams({limit:50,offset});$('opsFilters').querySelectorAll('[data-filter]').forEach(e=>{if(e.value)p.set(e.dataset.filter,e.value);});return p;}
  async function navigate(page,reset=false){
    await login();current=page;if(reset)offset=0;
    main.querySelectorAll('[data-page]').forEach(e=>e.hidden=e.dataset.page!==(page==='dashboard'?'dashboard':'ops'));
    nav.querySelectorAll('button').forEach(e=>e.classList.toggle('active',e.dataset.pageButton===page));
    section.hidden=page==='dashboard';
    if(page==='dashboard'){await showSummary();return;}
    $('opsTitle').textContent=titles[page];filters(page);$('opsAdd').hidden=!['finance','tasks'].includes(page);$('opsNotice').textContent='';$('opsStats').replaceChildren();await list();
  }
  async function showSummary(){
    summary=await api('/admin/ops/summary');
    dashboard={summary:{projected_monthly_revenue:summary.expected_mrr},plans:[],cities:[],product_categories:summary.product_categories,shops:[]};
    const delta=x=>[x.today>0?`+${x.today} сегодня`:'Сегодня новых записей нет',x.week>0?`+${x.week} за 7 дней`:'За 7 дней новых записей нет'].join(' · ');
    const card=(label,value,note)=>`<article class="panel metric"><span>${escape(label)}</span><strong>${fmt(value)}</strong><small>${escape(note||'')}</small></article>`;
    $('metrics').innerHTML=card('Ожидаемый MRR',money(summary.expected_mrr),'Сумма активных тарифов · PAYMENT: DISABLED')+card('Активные магазины',summary.stores.active,delta(summary.stores))+card('Покупатели',summary.buyers.total,delta(summary.buyers))+card('Товары',summary.products.total,delta(summary.products))+card('QR-сделки',summary.qr.total,delta(summary.qr))+card('Требуют внимания',summary.attention.reduce((a,x)=>a+x.count,0),'Операционные сигналы; один объект может иметь несколько сигналов');
    const events=(types)=>{const found=summary.events.filter(x=>types.includes(x.event_type));return found.length?found.reduce((n,x)=>n+Number(x.today||0),0):null;};
    $('opsToday').innerHTML=[['Новые покупатели',summary.buyers.today],['Новые продавцы',summary.sellers.today],['Новые магазины',summary.stores.today],['Новые товары',summary.products.today],['Поисковые запросы',summary.searches_today],['Просмотры товаров',events(['product_view'])],['Просмотры магазинов',events(['store_view'])],['Route clicks',events(['route_request'])],['Начатые чаты',summary.chats_today],['QR-сделки',summary.qr.today]].map(([l,v])=>card(l,v)).join('');
    const reasons={pending_stores:['Магазины на проверке','stores',{verification:'unverified'}],empty_stores:['Магазины без товаров','stores',{products:'no'}],reports:['Жалобы','moderation',{}],blocked_users:['Заблокированные аккаунты','users',{status:'blocked'}],push_jobs:['Проблемные push jobs','operations',{}],media_jobs:['Ошибки media jobs','operations',{}],pos_jobs:['Failed POS sync','operations',{}],import_jobs:['Failed imports','operations',{}],store_errors:['Ошибки интеграций магазина','operations',{}],stuck_jobs:['Зависшие задачи','operations',{}],analytics_jobs:['Ошибки аналитики','operations',{}]};
    $('opsAttention').innerHTML=summary.attention.filter(x=>x.count>0).map(x=>`<button class="action" data-attention="${escape(x.kind)}">${escape(reasons[x.kind]?.[0]||x.kind)}: ${x.count}</button>`).join('')||'Нет обнаруженных проблем';
    $('opsAttention').querySelectorAll('[data-attention]').forEach(b=>b.onclick=safely(async()=>{const [,page,params]=reasons[b.dataset.attention];await navigate(page,true);for(const [k,v] of Object.entries(params))$('opsFilters').querySelector(`[data-filter="${k}"]`).value=v;await list();}));
    renderBars('plans',summary.plans.map(p=>({...p,shops_count:p.count})),p=>labels[p.plan],p=>`${p.count} магаз. · ${summary.stores.total?Math.round(p.count/summary.stores.total*100):0}% · ${money(p.count*p.price)}`);
    renderBars('cities',summary.geography.map(p=>({...p,city:[p.city,p.district].filter(Boolean).join(' / ')||'Не указан',shops_count:p.stores})),p=>p.city,p=>`${p.stores} магаз. · ${p.products} товаров`);
    renderBars('categories',summary.product_categories,p=>p.category,p=>`${p.products_count} товаров · ${p.shops_count} магаз.`,p=>p.products_count);
    $('opsDashboardNotes').innerHTML=table(summary.notes,[['Задача',x=>escape(x.title||x.body)],['Priority / status',x=>escape(x.priority)+' / '+escape(x.status)],['Срок',x=>escape(String(x.due_date||'—').slice(0,10))]]);
    $('opsDashboardFinance').innerHTML=table(Object.entries(summary.finance).map(([key,value])=>({key,value})),[['Показатель (UZS)',x=>escape(x.key)],['Сумма',x=>money(x.value)]]);
    const recent=await api('/admin/ops/stores?limit=10');$('opsRecentStores').innerHTML=table(recent.items,[['Магазин',x=>`<button class="action" data-recent-store="${x.id}">${escape(x.name)} #${x.id}<small>${x.root_shop_id?"ФИЛИАЛ":"Основной филиал"} · ${escape(x.store_code)}</small></button>`],['Город',x=>escape(x.city)],['Тариф',x=>escape(labels[x.plan]||x.plan)],['Товары / QR',x=>fmt(x.product_count)+' / '+fmt(x.qr_deals)]]);$('opsRecentStores').querySelectorAll('[data-recent-store]').forEach(b=>b.onclick=safely(()=>storeDetail(b.dataset.recentStore)));
    $('opsGeo').innerHTML=table(summary.geography,[['Страна',x=>escape(x.country||'Не указана')],['Город',x=>escape(x.city||'Не указан')],['Район',x=>escape(x.district||'Не указан')],['Магазины',x=>fmt(x.stores)],['Активные',x=>fmt(x.active_stores)],['Товары',x=>fmt(x.products)],['QR-сделки',x=>fmt(x.qr_deals)],['Growth target',x=>x.target?`${x.stores} / ${x.target} · ${Math.round(x.stores/x.target*100)}%`:'Не установлен']]);
    const funnel=await api('/admin/ops/funnels');$('opsFunnels').innerHTML=['seller','buyer'].map(k=>'<h3>'+escape(k==='seller'?'Seller funnel':'Buyer funnel')+'</h3>'+table(Object.entries(funnel[k]).map(([stage,count],i,all)=>({stage,count,conversion:i&&all[i-1][1]>0?Math.round(count/all[i-1][1]*100)+'%':'—'})),[['Этап',x=>escape(x.stage)],['Аккаунты',x=>fmt(x.count)],['Переход',x=>fmt(x.conversion)]])).join('')+`<p class="muted">${escape(funnel.method)}</p>`;
  }
  async function list(){
    const requestGeneration=++generation;const page=current;$('opsRows').innerHTML='<p role="status">Загрузка данных…</p>';$('opsReload').disabled=true;
    try {
      if(page==='moderation'){$('opsPaging').hidden=true;$('opsRows').innerHTML='<p>Очереди модерации используют существующие действия с подтверждением.</p>'+['stores','products','reviews','users','reports'].map(p=>`<button class="action" data-queue="${p}">${p}</button>`).join('');$('opsRows').querySelectorAll('[data-queue]').forEach(b=>b.onclick=safely(async()=>{if(['reviews','reports'].includes(b.dataset.queue)){section.hidden=true;await window.MapMarketControl.navigate(b.dataset.queue);}else{await navigate(b.dataset.queue,true);if(b.dataset.queue==='stores'){$('opsFilters').querySelector('[data-filter="verification"]').value='unverified';await list();}}}));return;}
      const data=await api(`/admin/ops/${page==='tasks'?'notes':page}?${query()}`);if(requestGeneration!==generation||page!==current)return;
      rowsData=data.items||data.jobs||[];const more=rowsData.length===50&&offset+rowsData.length<Number(data.total||0);$('opsPaging').hidden=page==='operations';$('opsPrev').disabled=offset===0;$('opsNext').disabled=!more;$('opsPageInfo').textContent=`${offset+1}–${offset+rowsData.length} / ${data.total??rowsData.length}`;
      const button=(kind,x,label)=>`<button class="action" data-${kind}="${escape(x.id)}">${escape(label)}</button>`;
      const columns={
        stores:[['Бизнес',x=>button('store',x,`${x.name} #${x.id}`)+(x.branches?.length>1?'<details><summary>'+x.branches.length+' филиалов</summary>'+x.branches.map(b=>'<p><button class="action" data-admin-branch="'+b.id+'">'+escape(b.is_main?'Основной филиал':b.name)+'</button><br>'+escape(b.code)+'<br>'+escape(b.address)+'</p>').join('')+'</details>':'')],['Общий AI кошелёк',x=>fmt(x.ai_credits_remaining)],['Владелец',x=>escape(x.owner)+'<br>'+escape(x.owner_phone)],['Адрес',x=>escape([x.country,x.city,x.district,x.address].filter(Boolean).join(', '))],['Телефон',x=>escape(x.phone)],['Категория',x=>escape(x.category)],['Координаты',x=>escape(`${x.latitude}, ${x.longitude}`)],['Проверка / статус',x=>escape(`${x.verification_status} / ${x.moderation_status}`)],['Тариф',x=>escape(labels[x.plan]||x.plan)+'<br>'+when(x.plan_started_at)+' → '+when(x.plan_expires_at)],['Товары / QR',x=>fmt(x.product_count)+' / '+fmt(x.qr_deals)],['Views / routes',x=>fmt(x.views)+' / '+fmt(x.routes)],['Chats / followers',x=>fmt(x.chats)+' / '+fmt(x.followers)],['Активность',x=>when(x.last_activity)],['Создан',x=>when(x.created_at)]],
        users:[['Аккаунт',x=>button('user',x,`${x.name} #${x.id}`)],['Телефон',x=>escape(x.phone)],['Verified',x=>x.phone_verified_at?'YES':'NO'],['Роль / статус',x=>escape(x.role)+' / '+(x.is_blocked?'BLOCKED':'ACTIVE')],['Регистрация',x=>when(x.created_at)],['Активность',x=>when(x.last_activity)],['Search / favorites',x=>fmt(x.searches)+' / '+fmt(x.favorites)],['Chats / QR / reports',x=>fmt(x.chats)+' / '+fmt(x.qr_deals)+' / '+fmt(x.reports)]],
        products:[['Товар',x=>button('product',x,`${x.title} #${x.id}`)],['Магазин',x=>escape(x.store)],['Категория / бренд',x=>escape(x.category)+' / '+escape(x.brand)],['Статус',x=>escape(x.status)],['Цена',x=>money(x.price)],['Stock',x=>fmt(x.stock_quantity)+(x.in_stock?' · Есть':' · Нет')],['Reports',x=>fmt(x.reports)]],
        search:[['Запрос',x=>escape(x.query)],['Search count',x=>fmt(x.search_count)],['Unique users',x=>fmt(x.unique_users)],['Results (returned page average)',x=>fmt(x.results_count)],['Zero results',x=>fmt(x.no_results)],['Измерено',x=>fmt(x.measured_searches)],['Clicks / product opens / store opens / routes / conversion',x=>[x.clicks,x.product_opens,x.store_opens,x.route_clicks,x.conversion===null?null:x.conversion+'%'].map(fmt).join(' / ')],['Последний поиск',x=>when(x.last_searched)]],
        qr:[['ID',x=>fmt(x.id)],['Buyer',x=>escape(x.buyer)],['Store / seller',x=>escape(x.store)+' / '+fmt(x.seller_id)],['Дата',x=>when(x.created_at)],['Amount quoted',x=>fmt(x.amount_quoted)],['Discount',x=>fmt(x.discount)],['Товар',x=>escape(x.product_reference)],['Статус',x=>escape(x.status)]],
        finance:[['ID / дата',x=>fmt(x.id)+' / '+escape(x.operation_date)],['Тип / категория',x=>escape(x.type)+' / '+escape(x.category)],['Сумма',x=>fmt(x.amount)+' '+escape(x.currency)],['Описание',x=>escape(x.description)],['Admin / created',x=>escape(x.created_by)+'<br>'+when(x.created_at)],['Действия',x=>button('edit',x,'Изменить')+' '+button('delete',x,'Удалить')]],
        tasks:[['Задача',x=>escape(x.title)+'<p>'+escape(x.body)+'</p>'],['Категория / priority',x=>escape(x.category)+' / '+escape(x.priority)],['Status',x=>escape(x.status)],['Due / completed',x=>escape(x.due_date||'—')+' / '+when(x.completed_at)],['Store',x=>fmt(x.shop_id)],['Действия',x=>button('edit',x,'Изменить')+' '+(x.status!=='DONE'?button('done',x,'Выполнено'):'')+' '+button('delete',x,'Удалить')]],
        audit:[['Дата / Admin',x=>when(x.created_at)+'<br>'+escape(x.admin_id)],['Действие / объект',x=>escape(x.action)+'<br>'+escape(x.entity_type)+' #'+fmt(x.entity_id)],['Причина',x=>escape(x.reason)],['Old → new',x=>escape(JSON.stringify(x.old_value))+' → '+escape(JSON.stringify(x.new_value))],['Request ID',x=>escape(x.request_id)]],
        operations:[['Тип / ID',x=>escape(x.type)+' / '+escape(x.id)],['Статус',x=>escape(x.status)+(x.stuck?' · STUCK':'')],['Ошибка',x=>escape(x.error)],['Attempts',x=>fmt(x.attempts)],['Создан / updated',x=>when(x.created_at)+' / '+when(x.updated_at)],['Действие',x=>x.status==='failed'&&['media','pos','analytics'].includes(x.type)?`<button class="action" data-retry="${escape(x.type+':'+x.id)}">Retry</button>`:x.type==='push'?'Повтор требует защиты от дубликатов':'—']]
      };
      $('opsRows').innerHTML=table(rowsData,columns[page]);
      $('opsNotice').textContent=page==='qr'?'PAYMENT: DISABLED / TEST MODE — SUCCESS означает завершение Yaqintop market QR flow.':page==='search'?'Исторические поиски без results_count не считаются zero results. Количество результатов — размер возвращённой страницы.':page==='finance'?'Collected subscription revenue: PAYMENT DISABLED. Валюты не складываются; balance — сумма записей журнала.':'';
      if(page==='operations'){
        $('opsStats').innerHTML=Object.entries(data.health).map(([k,v])=>`<article class="metric"><span>${escape(k)}</span><strong>${escape(v)}</strong></article>`).join('');
        $('opsNotice').textContent='UNKNOWN: provider не проверен. Push retry запрещён без защиты от повторной доставки. AI jobs выполняются синхронно, постоянной очереди нет.';
        $('opsRows').insertAdjacentHTML('beforeend','<h3>Running / queued / failed / retries</h3>'+table(data.stats,[['Тип',x=>escape(x.type)],['Статус',x=>escape(x.status)],['Количество',x=>fmt(x.count)],['Retries',x=>fmt(x.retries)],['Последнее выполнение',x=>when(x.last_execution)]])+'<h3>Фоновые workers</h3>'+table(data.workers,[['Worker',x=>escape(x.name)],['Status',x=>x.ok?'HEALTHY':'FAILED'],['Обработано',x=>fmt(x.processed)],['Последнее выполнение',x=>when(x.last_execution)]])+'<h3>Imports</h3>'+table(data.imports,[['ID',x=>escape(x.id)],['Store',x=>fmt(x.store_id)],['Status',x=>escape(x.status)],['Количество строк',x=>fmt(x.total_count)],['Дата',x=>when(x.created_at)]])+'<h3>POS Integrations</h3>'+table(data.integrations,[['ID / store',x=>fmt(x.id)+' / '+fmt(x.store_id)],['Status',x=>escape(x.status)],['Error code',x=>escape(x.last_error_code)],['Последняя синхронизация',x=>when(x.last_sync_at)]]));
      }
      if(page==='finance')$('opsStats').innerHTML=Object.entries(data.summary).map(([k,v])=>`<article class="metric"><span>${escape(k)}</span><strong>${fmt(v)}</strong></article>`).join('')+`<article class="metric"><span>Expected MRR (UZS)</span><strong>${money(data.expected_mrr)}</strong></article>`;
      bind();
    }catch(e){if(requestGeneration===generation)$('opsRows').innerHTML='<p class="error">'+escape(e.message)+'</p>';throw e;}finally{$('opsReload').disabled=false;}
  }
  const guard=async(expected)=>{const reason=window.prompt('Причина (минимум 3 символа):');if(!reason)return null;const confirmation=window.prompt('Введите '+expected);if(confirmation===null)return null;return {reason,confirmation};};
  function bind(){
    $('opsRows').querySelectorAll('[data-admin-branch]').forEach(b=>b.onclick=safely(()=>window.MapMarketControl.branchDetail(b.dataset.adminBranch)));
    $('opsRows').querySelectorAll('[data-store]').forEach(b=>b.onclick=safely(()=>storeDetail(b.dataset.store)));
    $('opsRows').querySelectorAll('[data-user]').forEach(b=>b.onclick=safely(()=>window.MapMarketControl.userDetail(b.dataset.user)));
    $('opsRows').querySelectorAll('[data-product]').forEach(b=>b.onclick=safely(()=>productDetail(b.dataset.product)));
    $('opsRows').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(rowsData.find(x=>String(x.id)===b.dataset.edit)));
    $('opsRows').querySelectorAll('[data-delete]').forEach(b=>b.onclick=safely(async()=>{const n=b.dataset.delete,p=current==='tasks'?'notes':'finance',v=await guard(`DELETE ${current==='tasks'?'TASK':'FINANCE'} ${n}`);if(!v)return;await api(`/admin/ops/${p}/${n}`,{method:'DELETE',body:JSON.stringify(v)});notify('Удалено');await list();}));
    $('opsRows').querySelectorAll('[data-done]').forEach(b=>b.onclick=safely(async()=>{const old=rowsData.find(x=>String(x.id)===b.dataset.done);await api('/admin/ops/notes/'+old.id,{method:'PATCH',body:JSON.stringify({...old,status:'DONE'})});notify('Задача выполнена');await list();}));
    $('opsRows').querySelectorAll('[data-retry]').forEach(b=>b.onclick=safely(async()=>{const [type,n]=b.dataset.retry.split(':'),v=await guard(`RETRY ${type.toUpperCase()} ${n}`);if(!v)return;await api(`/admin/ops/jobs/${type}/${n}/retry`,{method:'POST',body:JSON.stringify(v)});notify('Повтор поставлен в очередь');await list();}));
  }
  const show=(title,html)=>{$('opsDetail').innerHTML='<h2>'+escape(title)+'</h2>'+html;if(!dialog.open)dialog.showModal();};
  const fields=value=>table(Object.entries(value||{}).map(([key,value])=>({key,value})),[['Поле',x=>escape(x.key)],['Значение',x=>escape(typeof x.value==='object'?JSON.stringify(x.value):x.value)]]);
  async function storeDetail(n){
    const [data,metrics]=await Promise.all([api('/admin/control/stores/'+n),api('/admin/ops/stores/'+n+'/metrics')]);
    show('Магазин #'+n,fields(data.store)+'<div class="actions">'+['verify','approve','reject','block','unblock','disable'].map(a=>`<button class="action" data-store-action="${a}">${a}</button>`).join('')+'<button id="opsPlan" class="action">Тариф ADMIN/PILOT</button><button id="opsStoreNote" class="action">Внутренняя заметка</button></div><h3>Метрики</h3>'+fields(metrics)+'<h3>Сотрудники</h3>'+table(data.staff,[['Имя',x=>escape(x.name)],['Роль',x=>escape(x.role)]])+'<h3>Филиалы</h3>'+table(metrics.branches,[['Филиал',x=>'<button class="action" data-admin-branch="'+x.id+'">'+escape(x.name)+'</button>'],['Код',x=>escape(x.store_code)],['Тип',x=>x.is_main?'Основной филиал':'ФИЛИАЛ'],['Адрес',x=>escape(x.address)]])+'<h3>Товары</h3>'+table(data.products,[['Товар',x=>escape(x.title)],['Цена',x=>money(x.price)]])+'<div class="actions"><button id="opsStoreProducts" class="action">Все товары</button><button id="opsStoreQR" class="action">QR история</button></div><h3>Подписки</h3>'+table(data.subscriptions,[['Тариф',x=>escape(labels[x.plan]||x.plan)],['Source',x=>escape(x.source)],['Start / end',x=>when(x.started_at)+' / '+when(x.expires_at)]]));
    $('opsDetail').querySelectorAll('[data-store-action]').forEach(b=>b.onclick=safely(async()=>{const a=b.dataset.storeAction,v=await guard(`${a.toUpperCase()} ${n}`);if(!v)return;await api('/admin/ops/stores/'+n+'/action',{method:'POST',body:JSON.stringify({...v,action:a})});notify('Статус обновлён');await storeDetail(n);}));
    $('opsDetail').querySelectorAll('[data-admin-branch]').forEach(b=>b.onclick=safely(async()=>{dialog.close();await window.MapMarketControl.branchDetail(b.dataset.adminBranch);}));
    $('opsPlan').onclick=()=>plan(data.store.root_shop_id||n);$('opsStoreNote').onclick=()=>edit({shop_id:Number(n)},'tasks');
    for(const [name,page] of [['opsStoreProducts','products'],['opsStoreQR','qr']])$(name).onclick=safely(async()=>{dialog.close();await navigate(page,true);$('opsFilters').querySelector('[data-filter="shop_id"]').value=n;await list();});
  }
  async function productDetail(n){
    const data=await api('/admin/ops/products/'+n),images=[...new Set([data.product.image_url,...(Array.isArray(data.product.image_urls)?data.product.image_urls:[])])].filter(Boolean);
    show('Товар #'+n,'<div class="ops-images">'+images.map(src=>`<img loading="lazy" alt="Фото товара" src="${escape(mediaUrl(src))}">`).join('')+'</div>'+fields(data.product)+'<div class="actions">'+['approve','reject','block','unblock'].map(a=>`<button class="action" data-product-action="${a}">${a}</button>`).join('')+'</div><h3>Master / offer</h3>'+fields(data.offer)+'<h3>Аналитика</h3>'+fields(data.analytics)+'<h3>Жалобы</h3>'+fields(data.reports)+'<button id="opsProductModeration" class="action">Открыть модерацию</button>');
    $('opsDetail').querySelectorAll('[data-product-action]').forEach(b=>b.onclick=safely(async()=>{const action=b.dataset.productAction,v=await guard(`${action.toUpperCase()} PRODUCT ${n}`);if(!v)return;await api('/admin/ops/products/'+n+'/action',{method:'POST',body:JSON.stringify({...v,action})});notify('Модерация сохранена');await productDetail(n);}));
    $('opsProductModeration').onclick=safely(async()=>{dialog.close();section.hidden=true;await window.MapMarketControl.navigate('reports');});
  }
  function form(title,definitions,submit){
    show(title,`<form id="opsForm">${definitions.map(([key,label,type,value,options])=>`<label>${escape(label)}${type==='select'?`<select name="${key}">${options.map(v=>`<option ${v===value?'selected':''}>${escape(v)}</option>`).join('')}</select>`:type==='textarea'?`<textarea name="${key}">${escape(value||'')}</textarea>`:`<input name="${key}" type="${type}" value="${escape(type==='date'?String(value??'').slice(0,10):value??'')}" ${type==='date'?'': 'maxlength="4000"'}>`}</label>`).join('')}<p id="opsFormError" class="error" role="alert"></p><button class="primary" type="submit">Сохранить</button></form>`);
    $('opsForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type="submit"]');button.disabled=true;$('opsFormError').textContent='';try{await submit(Object.fromEntries(new FormData(e.target)));dialog.close();notify('Сохранено');if(current==='dashboard')await showSummary();else await list();}catch(err){$('opsFormError').textContent=err.message;}finally{button.disabled=false;}};
  }
  function edit(old={},type=current){
    const today=new Date().toISOString().slice(0,10),isTask=type==='tasks';
    const defs=isTask?[['title','Название','text',old.title],['body','Описание','textarea',old.body],['category','Категория','select',old.category||'Other',config.note_categories],['priority','Priority','select',old.priority||'MEDIUM',['LOW','MEDIUM','HIGH','CRITICAL']],['status','Status','select',old.status||'TODO',['TODO','IN_PROGRESS','DONE']],['due_date','Срок','date',old.due_date],['shop_id','Store ID','number',old.shop_id]]:
      [['amount','Сумма (расход отрицательный)','number',old.amount],['description','Описание','text',old.description],['type','Тип','select',old.type||'expense',['income','expense','adjustment']],['category','Категория','select',old.category||'Other',config.finance_categories],['currency','Валюта','select',old.currency||'UZS',['UZS','USD','EUR']],['date','Дата','date',old.operation_date||today],['reason','Причина изменения','text','']];
    form(isTask?'Задача':'Финансовая операция',defs,async values=>{if(!isTask){const confirmation=window.prompt('Введите '+(old.id?`EDIT FINANCE ${old.id}`:'ADD FINANCE'));if(confirmation===null)throw new Error('Сохранение отменено.');values.confirmation=confirmation;}await api('/admin/ops/'+(isTask?'notes':'finance')+(old.id?'/'+old.id:''),{method:old.id?'PATCH':'POST',body:JSON.stringify(values)});});
  }
  function plan(n){const today=new Date().toISOString().slice(0,10);form('Тариф ADMIN/PILOT · PAYMENT DISABLED',[['plan','Тариф','select','FREE',config.plans.map(p=>p.name)],['start','Начало','date',today],['end','Окончание','date',new Date(Date.now()+30*86400000).toISOString().slice(0,10)],['reason','Причина','text','']],async values=>{values.confirmation=window.prompt('Введите PLAN '+n);await api('/admin/ops/stores/'+n+'/plan',{method:'POST',body:JSON.stringify(values)});});}
  $('opsTarget').onclick=()=>form('Growth target',[['country','Страна','text',''],['city','Город','text',''],['district','Район','text',''],['target','Цель (магазины)','number',''],['reason','Причина','text','']],async values=>{values.confirmation=window.prompt('Введите SET TARGET');await api('/admin/ops/growth-target',{method:'POST',body:JSON.stringify(values)});});
  $('opsDashboardAddTask').onclick=()=>edit({},'tasks');$('opsDashboardAddFinance').onclick=()=>edit({},'finance');
  $('opsAdd').onclick=()=>edit();$('opsReload').onclick=safely(list);$('opsPrev').onclick=safely(async()=>{offset=Math.max(0,offset-50);await list();});$('opsNext').onclick=safely(async()=>{offset+=50;await list();});
})();
